### ISSUE TITLE
Cloud Foundry

### ISSUE THREAD

**Issue by paulgovan** [fxi/shinyCluster#1]
Do you have any guidance on using this framework for deploying a shiny app to cloud foundry?

**Comment by fxi** [comment]
Hi,

No, sorry. 

FYI, this project is experimental and not really maintained. 

I'm curious, why do you want to use this project ?

Have you tried the solution bellow  ?

- http://www.shinyapps.io/
- R with heroku, eg. https://github.com/virtualstaticvoid/heroku-buildpack-r/tree/cedar-14-chroot

**Comment by paulgovan** [comment]
Thanks for the feedback. Yep, I'm familiar with shinyapps and the heroku buildpack. Actually, I'm currently experimenting with the buildpack. 

Basically, I'm trying to run a JavaScript buildpack for assets and a R buildpack my shiny app. I'm new to cloud foundry, so I don't even know if this is possible.
